"""Unit tests for detect_acd_version (acd.l5x.export_l5x).

The Studio version selects the V21 source-protection rung path, and it comes from
the container's Version.Log stream -- one line per save, so its length tracks the
project's save history rather than the format. These fixtures build real ACD
containers (file table at the tail, per the acd.zip.unzip layout) and pin that the
read follows the stream rather than a fixed slice of the file head.
"""

import gzip
import struct

from acd.l5x.export_l5x import detect_acd_version

V_OLD = "V10.00.00/3071"
V_NEW = "V31.02.00/3708.002"


def _entry(version, n):
    return "Saved - %s by someone on some date, revision %d\r\n" % (version, n)


def _container(streams):
    """A minimal ACD container: payloads, then a 528-byte-per-record file table.

    Mirrors acd.zip.unzip: AcdHeader reads (no_files, _unknown_two) from the LAST
    8 bytes and locates the table at file_size - no_files*528 - 8; each FileRecord
    is a NUL-terminated UTF-16-LE name padded to 520 bytes, then (length, offset).
    """
    blob = b""
    placed = []
    for name, payload in streams:
        placed.append((name, len(payload), len(blob)))
        blob += payload
    table = b""
    for name, length, offset in placed:
        encoded = name.encode("utf-16-le") + b"\x00\x00"
        table += encoded + b"\x00" * (520 - len(encoded)) + struct.pack("II", length, offset)
    return blob + table + struct.pack("II", len(placed), 0)


def _write(tmp_path, streams, name="p.ACD"):
    p = tmp_path / name
    p.write_bytes(_container(streams))
    return p


# A real Version.Log opens with this banner, and Unzip keys the container's magic
# number off its first two bytes.
_LOG_HEAD = "\r\nThis file was generated by the RSLogix 5000 software.\r\n\r\n"


def _log(n_old, version_new=V_NEW):
    """A Version.Log whose history is n_old old saves then one newer save."""
    body = "".join(_entry(V_OLD, i) for i in range(n_old))
    return (_LOG_HEAD + body + _entry(version_new, n_old)).encode("latin1")


def test_reads_the_last_save(tmp_path):
    p = _write(tmp_path, [("Version.Log", _log(3))])
    assert detect_acd_version(p) == V_NEW


def test_long_save_history_still_reads_the_last_save(tmp_path):
    # THE REGRESSION: Version.Log runs to 175 KB on the pool's most-edited
    # project. A fixed read of the file head truncates the log mid-history and
    # returns some middle save -- here it would report V10 for a V31 project.
    log = _log(4000)
    assert len(log) > 8192
    p = _write(tmp_path, [("Version.Log", log)])
    assert detect_acd_version(p) == V_NEW


def test_a_nested_container_after_the_log_is_not_read(tmp_path):
    # ProjectTemplate.ACD is itself a container with its OWN Version.Log, so a
    # read that runs past Version.Log finds a FOREIGN project's saves.
    p = _write(tmp_path, [
        ("Version.Log", _log(2)),
        ("ProjectTemplate.ACD", _entry("V99.00.00/9999.000", 0).encode("latin1")),
    ])
    assert detect_acd_version(p) == V_NEW


def test_gzipped_log_is_decompressed(tmp_path):
    # Container streams may be gzip-compressed (Unzip.write_files keys off the
    # same magic). Version.Log leads the real containers, and Unzip takes the
    # container's own magic from the first two bytes of the file, so a compressed
    # Version.Log cannot lead one -- put it second to exercise the branch.
    p = _write(tmp_path, [
        ("Comps.Dat", b"\r\n" + b"x" * 32),
        ("Version.Log", gzip.compress(_log(3))),
    ])
    assert detect_acd_version(p) == V_NEW


def test_log_is_located_by_name_not_position(tmp_path):
    p = _write(tmp_path, [
        ("TextualVersionInfo.Dat", b"\r\n" + b"junk" * 64),
        ("Version.Log", _log(2)),
    ])
    assert detect_acd_version(p) == V_NEW


def test_no_version_log_stream(tmp_path):
    p = _write(tmp_path, [("Comps.Dat", b"\r\n" + b"x" * 32)])
    assert detect_acd_version(p) is None


def test_version_log_without_a_banner(tmp_path):
    p = _write(tmp_path, [("Version.Log", b"\r\nno banner here")])
    assert detect_acd_version(p) is None


def test_missing_file_returns_none(tmp_path):
    assert detect_acd_version(tmp_path / "nope.ACD") is None


def test_unreadable_container_returns_none(tmp_path):
    p = tmp_path / "junk.ACD"
    p.write_bytes(b"\x00" * 4)
    assert detect_acd_version(p) is None
